### PR TITLE
Add twitter proxy configuration

### PR DESCRIPTION
**Pull request by Bobface**
Adds the option to provide a proxy configuration for the Twitter provider via environment variables.

### CODE REVIEW

**Comment by Kikobeats** [comment]
@Bobface what do you think if proxy details are provided via query parameters? then people can still use unavatar.now.sh

**Comment by Bobface** [comment]
@Kikobeats  Hmm, two problems come to mind:

- Server running unavatar can be abused for DDos amplification attack. Imagine this proxy option is implemented for all providers and proxy url can be provided via query parameters. You can provide your DDoS target as proxy URL. With 15 providers and some of them doing 2 requests (like Twitter), 1 malicious request to unavatar results in 20 outgoing requests to the DDoS target -> x20 amplification

- We could not use an authed or private proxy in most scenarios because the client making the request to unavatar would have to know proxy credentials. If the client is something like a website then proxy credentials can be extracted from the source.

**Comment by Bobface** [comment]
@Kikobeats ping

**Comment by Kikobeats** [comment]
The problem is I'm not seeing this resolve the issue for most users. Yea, you can self-host your own server, but ideally, I want to find a solution that can be landed at unavatar.now.sh

**Comment by Kikobeats** [comment]
Closing since the issue was mitigated; also check https://unavatar.io/#twitter

**Pull request closed without merging**
