### PR TITLE
Ensure Instagram avatar URL is properly encoded

### PR DESCRIPTION
**Pull request by rodrigoreis22**
Instagram is now encoding the &'s on their URLs with the ASCII code \u0026. This fix makes the replacement before returning.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Can you write the URL that is failing for you?

**Comment by rodrigoreis22** [comment]
The error occurs for any instagram profile:
https://www.instagram.com/willsmith/

will have this URL as property:

```
https://scontent-sjc3-1.cdninstagram.com/v/t51.2885-19/s320x320/53705764_2304835803071421_4142165059826614272_n.jpg?_nc_ht=scontent-sjc3-1.cdninstagram.com\u0026_nc_ohc=lEqIpND4vyoAX921vma\u0026oh=ee489578b67569fb523f67f264d9c6ca\u0026oe=5F089FF3
```

**Comment by LynchEntrostat** [comment]
@Kikobeats just wanted to know if this Instagram url issue was resolved. Checked again today and it doesn't seem to work with the example.
:pray: Thank you for your work!

**Comment by Kikobeats** [comment]
@LynchEntrostat it's a thing related with the codebase

Instagram is now showing a "wall" login so in order to retrieve the avatar you need to be authenticated or at least simulate a browser navigation behavior :(

**Comment by LynchEntrostat** [comment]
> @LynchEntrostat it's a thing related with the codebase
> 
> Instagram is now showing a "wall" login so in order to retrieve the avatar you need to be authenticated or at least simulate a browser navigation behavior :(
Alright :cry: :sob:

**Comment by DRSDavidSoft** [comment]
@Kikobeats That's a bummer, the auth wall is also being triggered for the `?__a=1` json page:
```
http://instagram.com/USERNAME?__a=1
```

**Comment by kehers** [comment]
@Kikobeats What's strange is that I ran something similar locally and it works. No auth wall. When I deployed on my server, I get the auth wall. I've even tried using a browser user-agent. Same.

**Comment by LynchEntrostat** [comment]
> @Kikobeats That's a bummer, the auth wall is also being triggered for the `?__a=1` json page:
> 
> ```
> http://instagram.com/USERNAME?__a=1
> ```

I used **curl** on such a link and I didn't hit an auth wall.
Maybe they fixed it :man_shrugging:

**Comment by Kikobeats** [comment]
@LynchEntrostat We tested that solution as well and it looks like it works because you are performing the request from your localhost.

unavatar.now.ish is running under AWS Lambda, meaning it has an IP Address from AWS production servers pool ranges. Instagram knows that and they block the IP after a while.

So the thing is, the IP access should be different every time, and that can be achieved using a proxy service.

That's the thing done by Microlink, where proxy rotation is done under the hood.

See the following example: https://microlink.io/docs/mql/getting-started/overview

Unfortunately, it isn't a free cost solution, I can't ship the workaround as part of this project.

(note that in case of Microlink, it is assuming the cost)

**Comment by DRSDavidSoft** [comment]
I'm pretty sure the source IP is not the _only_ factor, since I'm getting the auth wall from my home as well as work network.

Is it feasible to pass some authentication cookies, or write a simple login mechanism using existing npm [packages](https://www.npmjs.com/search?q=instagram&ranking=maintenance)?  Or would it make more sense to utilize the official [Instagram APIs](https://www.instagram.com/developer/endpoints/)?

Regarding using a proxy, would routing through Tor work if we come up with a solution to pass the data from AWS?

**Comment by kehers** [comment]
@Kikobeats I think Microlink uses Puppeteer under the hood. Tested Puppeteer on Instagram and it worked. Puppeteer's response time is really high though. It's amazing how Microlink can get it under ~3secs. Oh, and concurrency is a mess.

**Pull request merged**
